### ISSUE TITLE
Issue: Error in file FileByAshish

### ISSUE THREAD

**Issue by AshishRanjeetJha** [pooja2125/devops#1]
Hey,
There's a build error in the below file:
(https://github.com/pooja2125/devops/blob/main/FileByAshish.java)

Please have a look **_@AshishRanjeetJha_**

**Comment by pooja2125** [comment]
ok ashish will look in to it

**Comment by pooja2125** [comment]
@chiragpujari can you plz check this issue

**Comment by AshishRanjeetJha** [comment]
It's solved now.
