### ISSUE TITLE
Facing issue in the code by Vibhin

### ISSUE THREAD

**Issue by vibhinu** [pooja2125/devops#5]
Hi Team,
Could you please anyone help me with a suggestion to proceed further with the below [code.]([training_Vibhin.txt](https://github.com/pooja2125/devops/files/6997720/training_Vibhin.txt))

**Comment by Kiruba-21** [comment]
Issue is resolved

**Comment by vibhinu** [comment]
Thanks you for resolving @Kiruba-21
